apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: crochunter-deployment
  namespace: fuze
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: crochunter
    spec:
      containers:
      - name: crochunter
        image: 329054710135.dkr.ecr.eu-west-2.amazonaws.com/k8s-fuze:BUILDNUMBER
        ports:
        - containerPort: 8080
