apiVersion: v1
kind: Service
metadata:
  name: crochunter
  labels:
    app: crochunter
spec:
  type: LoadBalancer
  ports:
  - port: 8998
    targetPort: 8080
    protocol: TCP
    name: crochunter
  selector:
    app: crochunter
